name: Barry Mutch Music
favicon: null
layout_spectrum: 0.9789208
typography_spectrum: 0.5303541
title: The Online Home Of Barry Mutch Music Studio Design - Equipment Sales - Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09002c'
    - '#fc01fd'
    - '#fffffe'
    - '#6991fd'
    - '#fb8ffd'
  brandStrength: 0.5625
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
