name: Barry Mutch Music
favicon: null
layout_spectrum: 0.49042
typography_spectrum: 0.59878
title: The Online Home Of Barry Mutch Music Studio Design - Equipment Sales - Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b6b6b'
    - '#8a8a8a'
    - '#050505'
    - '#2a2c2b'
    - '#acacac'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
