layout_spectrum: 0.9789208
color:
  saturation: 0.2993255
  lightness: 0.03204047
  brandStrength: 0.5252951
  brandColors:
    - '#0000FD'
    - '#00016E'
    - '#FFFFFF'
    - '#A303FF'
    - '#544BA2'
  rhythmicContrast: 0.3524452
typography_spectrum: 0.5303541
name: Barry Mutch Music
